const words: string[] = [
'DINOSAURIO',
'MURCIELAGO',
'CONSPIRACION',
'VETERINARIO',
'CHINACOTA',
'COMPUTADORA',
'CARRETERA',
'DIOSESAMOR',
'ALEJANDRIA',
'EXTRATERRESTRE',
'GOLONDRINA',
'VEHICULO',
'ZAPATILLA',
'URBANIZACION',
'CEMENTERIO',
'AGUAZULIA',
'VENTRILOCO',
'XILOFONO',
'BARRANQUILLA',
'BIBLIOTECA',
'VENEZUELA',
'BARRANCABERMEJA',
'DICCIONARIO',
'ELECTRICIDAD',
'DICTAMINAR',
'BALLESTERIA',
'ORNITORRINCO',
'ELECTRODOMESTICO',
'EXTERNOCLEIDOMASTOIDEO',
'BOCAGRANDE',
'DOSMILVEINTICUATRO',
'AGUACATE',
]


export function getRandomWord() {
    const randomIndex = (Math.floor(Math.random() * words.length));
    return words[randomIndex];
}